name: Convert CSV to JSON for Database updates

on:
  push:
    paths:
      - 'db/**'
  pull_request:
    paths:
      - 'db/**'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    # Checkout project
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pandas
      run: pip install pandas

    - name: Convert CSV to JSON
      run: |
        python -c "import os; import pandas as pd; os.makedirs('db/json', exist_ok=True); csv_files = [f for f in os.listdir('db/csv') if f.endswith('.csv')]; [pd.read_csv(f'db/csv/{file}').to_json(f'db/json/{file.replace('.csv', '.json')}', orient='records', lines=True) for file in csv_files]"


    - name: Upload JSON files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: json-files
        path: db/json/