name: Convert CSV to JSON for Database updates

on:
  push:
    paths:
      - 'db/**'
  pull_request:
    paths:
      - 'db/**'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    # Checkout project
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install pandas
      run: pip install pandas

    - name: Install regex
      run: pip install regex

    - name: Install json
      run: pip install json

    - name: Convert CSV to JSON
      run: python db/convert-csv-to-json.py

    - name: Upload JSON files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: json-files
        path: db/json/